### ISSUE TITLE
TODO V2

### ISSUE THREAD

**Issue by vlakam** [FireX-Proxy/X.Scraper#11]
- [x] Сделать граб при старте (шедулер начинает работать после первого граба и проверки)
- [x] Разобраться почему unhandled rejection при фейле подключения к X.Meter
- [x] Переделать логику записи информации о прокси-серверах в базу данных
